version: "3.9"

services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: production
    volumes:
      - ./card-coupon-db/production:/app/card-coupon-db
    ports:
      - "5500:5000"
    working_dir: /app  # Set the working directory inside the container to /app

  testing:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: testing
    volumes:
      - ./card-coupon-db/testing:/app/card-coupon-db
    ports:
      - "5555:5000"
    working_dir: /app  # Set the working directory inside the container to /app

  development:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
    volumes:
      - ./card-coupon-db/development:/app/card-coupon-db
    ports:
      - "5050:5000"
    working_dir: /app  # Set the working directory inside the container to /app
