version: "3.9"

services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: production
    volumes:
      - ./card-coupon-db/production:/app/card-coupon-db
    ports:
      - "5500:5000"
  
  testing:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: testing
    volumes:
      - ./card-coupon-db/testing:/app/card-coupon-db
    ports:
      - "5555:5000"
